### ISSUE TITLE
NIEM UML 3.0 status?

### ISSUE THREAD

**Issue by Thwar** [NIEM/NIEM-UML#1]
I am an new active developer in NIEM UML. I am having a hard time finding people working with the same tool/plugin. There isn't a lot of support or resources or even examples for such tool. I feel like I am just throwing darts into the dark. I am currently working on the Eclipse environment, but I am not sure if that is the adequate environment for NIEM UML. I'd like to cooperate with other developers using NIEM-UML , I've been done some progress on my own and I'd like to share.

-Questions:
What is the status for the 3.0 version? 
Also, what is the relationship between these repositories: 
https://github.com/niem/niem-uml
https://github.com/info-sharing-environment/NIEM-Modeling-Tool

**Comment by CB2** [comment]
Hi Thomas,
Thanks for reaching out.  It’s always great to hear from NIEM community developers!

Regarding NIEM-UML status for NIEM version 3.0, the NIEM-UML profile just got approved by the Object Management Group’s Architecture Board last Tuesday (March 24).  We are now actively working with UML tool providers such as No Magic and Sparx Systems to incorporate NIEM-UML 3.0 into their tools, as they did for NIEM-UML 2.1.

We would love to learn more about your work with NIEM and your use of NIEM-UML.  We’re currently looking for case studies for how NIEM-UML is being used and implemented, more on this can be found at https://niem.gov/uml. 

Feel free to share your progress on this GitHub thread for others to access or by emailing us at information@niem.gov. 

Look forward to hearing from you!

-Christina
NIEM Team

**Comment by tomsantos** [comment]
Hi, 

I notice with interest that you have some Eclipse files under your Resource directory. I've imported these to have a bit of a look around without much success. Is there any documentation on how these can be used?

tom
